version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: db_mongo
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  backend:
    container_name: backend_nodejs
      - mongodb
    build: ./backend
    volumes:
      - ./backend:/backend
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
  front:
    container_name: frontend_react
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

volumes:
  db: